---

#================================================
# Documentation
#    https://github.com/spaam/svtplay-dl
#================================================


#================================================
# Install packages and application
#================================================



# A) To install from source (Python) run this 





# Ubuntu 16 = xenial
# Ubintu 18 = bionic
 

#--- Packages tailored for a certain distro or release
- name: Include specific packages for {{ansible_distribution}}-{{ansible_distribution_release}}
  include:  packages-{{ansible_distribution}}-{{ansible_distribution_release}}.yml






- name: Git Checkout and Update the svtplay-dl package
  git:
    repo: 'https://github.com/spaam/svtplay-dl'
    dest: "{{svtdl_dir}}"
    update: yes
    version: master
  tags: gitto




- name: Install the svtplay-dl package
  become: yes
  become_method: sudo
  shell: "cd {{svtdl_dir}}; python3 setup.py install"






#================================================
# Deprecated: 
# Installation of the prepackaged version
#================================================

# B) To install the prepackaged version, include this
#- include: svtdl-prepackaged.yml

