---



- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: true
  tags: bbb



- name: Install required packages
  package:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
    - curl
    - git
    - python3-pip
    - python-setuptools   #Installing both v2 and v3 for now, to compensate for the version-mixups between Ansible vs host
    - python3-setuptools
    - ffmpeg
  tags: bbb


- name: Upgrade pip3 to latest version
  become: yes
  become_method: sudo
  shell: "pip3 install --upgrade pip"
  tags: bbb



# Ubuntu 18.04 ships with Python 3, as the default Python installation.
# But still we need to specify the usage of pip3

- name: Install Python3 packages
  pip: 
    name: "{{ packages }}"
    state: present
    executable: /usr/local/bin/pip3
  become: true
  vars:
    packages:
    - cryptography
    - PyYaml
    - Requests
    - PySocks
  tags: bbb
